/**
 * PES Curve Visualization Tests (US-041)
 *
 * Validates:
 * - Golden test data structure for H2 STO-3G PES scan
 * - PES point type structure and constraints
 * - Equilibrium values within tolerance of PySCF reference
 * - PES artifact data schema validation
 *
 * @module components/scf/__tests__/pesCurve.test
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { PesScanArtifactDataSchema, PesArtifactPointSchema } from '../../../types/run-artifact';

// ============================================================================
// Load golden test data
// ============================================================================

/**
 * Golden PES data from PySCF for H2/STO-3G.
 *
 * Generated by US-038 and stored at tests/golden/pes/h2_sto3g_pes.json.
 */
interface GoldenPesData {
  pyscf_version: string;
  molecule: string;
  basis: string;
  unit: string;
  scan_range: {
    r_min: number;
    r_max: number;
    n_points: number;
  };
  points: Array<{
    r_bohr: number;
    energy: number;
    converged: boolean;
    iterations: number;
  }>;
  equilibrium: {
    r_bohr: number;
    energy_hartree: number;
    energy_precise: number;
  };
}

function loadGoldenData(): GoldenPesData {
  const goldenPath = resolve(__dirname, '../../../../../../tests/golden/pes/h2_sto3g_pes.json');
  const raw = readFileSync(goldenPath, 'utf-8');
  return JSON.parse(raw) as GoldenPesData;
}

// ============================================================================
// Tests
// ============================================================================

describe('PES Golden Data Structure (AC-6)', () => {
  const golden = loadGoldenData();

  it('has correct metadata', () => {
    expect(golden.molecule).toBe('H2');
    expect(golden.basis).toBe('sto-3g');
    expect(golden.unit).toBe('bohr');
    expect(golden.pyscf_version).toBe('2.11.0');
  });

  it('has expected number of scan points', () => {
    expect(golden.points).toHaveLength(20);
    expect(golden.scan_range.n_points).toBe(20);
  });

  it('has scan range from 0.5 to 5.0 bohr', () => {
    expect(golden.scan_range.r_min).toBe(0.5);
    expect(golden.scan_range.r_max).toBe(5.0);
  });

  it('all points have required fields', () => {
    for (const point of golden.points) {
      expect(typeof point.r_bohr).toBe('number');
      expect(typeof point.energy).toBe('number');
      expect(typeof point.converged).toBe('boolean');
      expect(typeof point.iterations).toBe('number');
    }
  });

  it('all points are in ascending R order', () => {
    for (let i = 1; i < golden.points.length; i++) {
      expect(golden.points[i].r_bohr).toBeGreaterThan(golden.points[i - 1].r_bohr);
    }
  });

  it('all energies are finite numbers', () => {
    for (const point of golden.points) {
      expect(Number.isFinite(point.energy)).toBe(true);
    }
  });

  it('all points converged for H2 STO-3G', () => {
    for (const point of golden.points) {
      expect(point.converged).toBe(true);
    }
  });

  it('R values span the full scan range', () => {
    const firstR = golden.points[0].r_bohr;
    const lastR = golden.points[golden.points.length - 1].r_bohr;
    expect(firstR).toBeCloseTo(0.5, 1);
    expect(lastR).toBeCloseTo(5.0, 1);
  });
});

describe('PES Equilibrium Validation (AC-5)', () => {
  const golden = loadGoldenData();

  it('equilibrium R is approximately 1.362 bohr', () => {
    expect(golden.equilibrium.r_bohr).toBeCloseTo(1.362, 2);
  });

  it('equilibrium energy matches PySCF within 1e-8 Ha', () => {
    // The golden data includes both interpolated and precise energy
    // The precise energy from PySCF is -1.1174293513968432 Ha
    // The interpolated energy is -1.1164214903785574 Ha
    // Our IQCP implementation should match PySCF within tolerance
    expect(golden.equilibrium.energy_precise).toBeCloseTo(-1.1174293513968432, 8);
  });

  it('energy minimum is in physically reasonable range', () => {
    // H2 STO-3G total energy should be around -1.1 Ha
    expect(golden.equilibrium.energy_hartree).toBeLessThan(-1.0);
    expect(golden.equilibrium.energy_hartree).toBeGreaterThan(-1.5);
  });

  it('equilibrium R is between first and last scan points', () => {
    const firstR = golden.points[0].r_bohr;
    const lastR = golden.points[golden.points.length - 1].r_bohr;
    expect(golden.equilibrium.r_bohr).toBeGreaterThan(firstR);
    expect(golden.equilibrium.r_bohr).toBeLessThan(lastR);
  });
});

describe('PES Artifact Schema Validation (AC-4)', () => {
  const golden = loadGoldenData();

  it('PesArtifactPoint validates individual points', () => {
    const point = golden.points[0];
    const result = PesArtifactPointSchema.safeParse({
      r_bohr: point.r_bohr,
      energy: point.energy,
      converged: point.converged,
      iterations: point.iterations,
    });
    expect(result.success).toBe(true);
  });

  it('PesScanArtifactData validates complete scan data', () => {
    const artifactData = {
      molecule: golden.molecule,
      basis: golden.basis,
      scan_parameter: 'bond_length',
      atom_indices: [0, 1],
      unit: golden.unit,
      points: golden.points.map((p) => ({
        r_bohr: p.r_bohr,
        energy: p.energy,
        converged: p.converged,
        iterations: p.iterations,
      })),
      equilibrium: {
        r_bohr: golden.equilibrium.r_bohr,
        energy_hartree: golden.equilibrium.energy_hartree,
      },
      compute_time_ms: 100,
    };

    const result = PesScanArtifactDataSchema.safeParse(artifactData);
    expect(result.success).toBe(true);
  });

  it('PesScanArtifactData validates with null equilibrium', () => {
    const artifactData = {
      molecule: 'H2',
      basis: 'sto-3g',
      scan_parameter: 'bond_length',
      atom_indices: [0, 1],
      unit: 'bohr',
      points: [],
      equilibrium: null,
      compute_time_ms: 0,
    };

    const result = PesScanArtifactDataSchema.safeParse(artifactData);
    expect(result.success).toBe(true);
  });

  it('PesScanArtifactData rejects invalid data', () => {
    const invalidData = {
      molecule: '',  // empty string should fail min(1)
      basis: 'sto-3g',
      scan_parameter: 'bond_length',
      atom_indices: [0, 1],
      unit: 'bohr',
      points: [],
      equilibrium: null,
      compute_time_ms: 0,
    };

    const result = PesScanArtifactDataSchema.safeParse(invalidData);
    expect(result.success).toBe(false);
  });
});

describe('PES Data Suitability for Plotly Rendering', () => {
  const golden = loadGoldenData();

  it('points can be split into x (R) and y (energy) arrays', () => {
    const xData = golden.points.map((p) => p.r_bohr);
    const yData = golden.points.map((p) => p.energy);

    expect(xData).toHaveLength(20);
    expect(yData).toHaveLength(20);
    expect(xData.every((x) => typeof x === 'number' && Number.isFinite(x))).toBe(true);
    expect(yData.every((y) => typeof y === 'number' && Number.isFinite(y))).toBe(true);
  });

  it('energy minimum is at an interior point (not at boundary)', () => {
    const energies = golden.points.map((p) => p.energy);
    const minIdx = energies.indexOf(Math.min(...energies));

    // Energy minimum should not be at the first or last point
    expect(minIdx).toBeGreaterThan(0);
    expect(minIdx).toBeLessThan(energies.length - 1);
  });

  it('PES curve has expected shape (minimum in middle, rises on both sides)', () => {
    const energies = golden.points.map((p) => p.energy);
    const minIdx = energies.indexOf(Math.min(...energies));

    // Points before minimum should be decreasing (approaching minimum from left)
    for (let i = 1; i <= minIdx; i++) {
      expect(energies[i]).toBeLessThanOrEqual(energies[i - 1]);
    }

    // Points after minimum should be increasing (moving away from minimum)
    for (let i = minIdx + 1; i < energies.length; i++) {
      expect(energies[i]).toBeGreaterThanOrEqual(energies[i - 1]);
    }
  });
});
