/**
 * Preset System Loader
 *
 * Imports and provides access to pre-computed molecular system data
 * for SCF calculations. These JSON files contain pre-computed integrals
 * (overlap, core Hamiltonian, ERIs) generated by PySCF.
 *
 * @module worker/presets
 */

// Import all preset JSON files
// Note: Vite handles JSON imports natively
import h2Preset from '../../../../content/presets/systems/h2_sto3g_r1.4.json';
import hehPlusPreset from '../../../../content/presets/systems/heh_plus_sto3g.json';
import lihPreset from '../../../../content/presets/systems/lih_sto3g.json';
import h2oPreset from '../../../../content/presets/systems/h2o_sto3g.json';
import nh3Preset from '../../../../content/presets/systems/nh3_sto3g.json';

/**
 * Type definition for the preset system JSON structure.
 *
 * Matches the format generated by PySCF in the preset generation scripts.
 * This structure contains all pre-computed integrals needed for RHF SCF.
 */
export interface PresetSystemJson {
  /** Format version for compatibility checking */
  format_version: number;
  /** Unique identifier for the system */
  system_id: string;
  /** Human-readable label */
  label: string;
  /** Optional description */
  description?: string;
  /** Geometry information (for reference only, not used in SCF) */
  geometry?: {
    atoms: Array<{ symbol: string; xyz: number[] }>;
    units: string;
  };
  /** Basis set identifier */
  basis_id: string;
  /** Number of basis functions */
  nbf: number;
  /** Number of electrons */
  nelec: number;
  /** Nuclear repulsion energy in Hartree */
  e_nuc: number;
  /** Overlap matrix (flattened, row-major, nbf x nbf) */
  s_matrix: number[];
  /** Core Hamiltonian matrix (flattened, row-major, nbf x nbf) */
  h_core: number[];
  /** Compressed two-electron integrals (8-fold symmetry) */
  eri_compressed: number[];
  /** Indexing scheme description */
  eri_indexing?: string;
  /** Reference data from PySCF */
  reference?: {
    software: string;
    version: string;
    energy: number;
  };
}

/**
 * Map of systemId to preset data.
 *
 * The keys match the `system_id` field in each JSON file.
 */
export const PRESETS: Record<string, PresetSystemJson> = {
  h2_sto3g_r1_4: h2Preset as PresetSystemJson,
  'h2_sto3g_r1.4': h2Preset as PresetSystemJson, // Allow both formats
  heh_plus_sto3g: hehPlusPreset as PresetSystemJson,
  lih_sto3g: lihPreset as PresetSystemJson,
  h2o_sto3g: h2oPreset as PresetSystemJson,
  nh3_sto3g: nh3Preset as PresetSystemJson,
};

/**
 * Cache for dynamically computed custom systems.
 *
 * Stores integral results from compute_integrals for use by SCF.
 * Keys are custom system IDs (e.g., "custom_79ef4a482cdafc21").
 */
const customSystemsCache: Map<string, PresetSystemJson> = new Map();

/**
 * Register a computed integral result as a custom system.
 *
 * Converts the camelCase IntegralComputeResult format to the snake_case
 * PresetSystemJson format expected by the WASM SCF function.
 *
 * @param systemId - The custom system ID
 * @param integralResult - The integral computation result (camelCase format)
 */
export function registerCustomSystem(
  systemId: string,
  integralResult: {
    formatVersion: number;
    label: string;
    description?: string;
    geometry?: {
      atoms: Array<{ symbol: string; xyz: number[] }>;
      units: string;
    };
    basisId: string;
    nbf: number;
    nelec: number;
    eNuc: number;
    sMatrix: number[];
    hCore: number[];
    eriCompressed: number[];
    eriIndexing?: string;
  }
): void {
  // Convert camelCase to snake_case format expected by WASM SCF
  const presetSystem: PresetSystemJson = {
    format_version: integralResult.formatVersion,
    system_id: systemId,
    label: integralResult.label,
    description: integralResult.description,
    geometry: integralResult.geometry,
    basis_id: integralResult.basisId,
    nbf: integralResult.nbf,
    nelec: integralResult.nelec,
    e_nuc: integralResult.eNuc,
    s_matrix: integralResult.sMatrix,
    h_core: integralResult.hCore,
    eri_compressed: integralResult.eriCompressed,
    eri_indexing: integralResult.eriIndexing,
  };

  customSystemsCache.set(systemId, presetSystem);
}

/**
 * Clear a custom system from the cache.
 *
 * @param systemId - The custom system ID to remove
 */
export function clearCustomSystem(systemId: string): void {
  customSystemsCache.delete(systemId);
}

/**
 * Clear all custom systems from the cache.
 */
export function clearAllCustomSystems(): void {
  customSystemsCache.clear();
}

/**
 * Get a preset system by its ID.
 *
 * Checks both built-in presets and dynamically computed custom systems.
 * Custom systems (from compute_integrals) take precedence if IDs collide.
 *
 * @param systemId - The system identifier (e.g., "h2_sto3g_r1.4" or "custom_...")
 * @returns The preset system data, or undefined if not found
 *
 * @example
 * ```typescript
 * const h2 = getPreset('h2_sto3g_r1.4');
 * if (h2) {
 *   console.log(`H2 has ${h2.nbf} basis functions`);
 * }
 *
 * // Also works for custom computed systems
 * const custom = getPreset('custom_79ef4a482cdafc21');
 * ```
 */
export function getPreset(systemId: string): PresetSystemJson | undefined {
  // Check custom systems cache first (allows overriding built-in presets if needed)
  const customSystem = customSystemsCache.get(systemId);
  if (customSystem) {
    return customSystem;
  }
  return PRESETS[systemId];
}

/**
 * List all available preset system IDs (built-in only).
 *
 * @returns Array of system IDs
 *
 * @example
 * ```typescript
 * const ids = listPresetIds();
 * // ['h2_sto3g_r1_4', 'h2_sto3g_r1.4', 'heh_plus_sto3g', 'lih_sto3g', 'h2o_sto3g', 'nh3_sto3g']
 * ```
 */
export function listPresetIds(): string[] {
  return Object.keys(PRESETS);
}

/**
 * List all available system IDs including custom systems.
 *
 * @returns Array of all system IDs (built-in + custom)
 */
export function listAllSystemIds(): string[] {
  const builtIn = Object.keys(PRESETS);
  const custom = Array.from(customSystemsCache.keys());
  return [...builtIn, ...custom];
}

/**
 * Get the count of custom systems currently cached.
 *
 * @returns Number of custom systems in cache
 */
export function getCustomSystemCount(): number {
  return customSystemsCache.size;
}

/**
 * List unique preset systems (removing duplicates).
 *
 * @returns Array of unique preset system data
 */
export function listPresets(): PresetSystemJson[] {
  // Use a Set to deduplicate by system_id
  const seen = new Set<string>();
  const result: PresetSystemJson[] = [];

  for (const preset of Object.values(PRESETS)) {
    if (!seen.has(preset.system_id)) {
      seen.add(preset.system_id);
      result.push(preset);
    }
  }

  return result;
}
