/**
 * POV-Ray scene exporter for IQCP molecular structures.
 *
 * Generates a complete .pov file from Atom3D[] data that can be
 * rendered with POV-Ray for publication-quality ray-traced images.
 *
 * Usage: Download the .pov file, then render with:
 *   povray +W1600 +H1200 +A molecule.pov
 *
 * @module lib/povrayExport
 */

import type { Atom3D } from '../components/viewer3d/AtomSpheres';
import type { LobeMeshData } from '../components/viewer3d/OrbitalSurface';
import type { CameraState } from '../components/viewer3d/MoleculeViewer';
import {
  CPK_COLORS,
  DEFAULT_ATOM_COLOR,
  COVALENT_RADII_BOHR,
  DEFAULT_COVALENT_RADIUS_BOHR,
  SPHERE_RADIUS_SCALE,
  BOND_TOLERANCE,
  BOHR_TO_ANGSTROM,
} from '../components/viewer3d/constants';

/** Convert hex color (#RRGGBB) to POV-Ray rgb<R, G, B> (0-1 range). */
function hexToPoV(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  return `rgb<${r.toFixed(4)}, ${g.toFixed(4)}, ${b.toFixed(4)}>`;
}

/** Detect bonds using the same criteria as the 3D viewer. */
function detectBonds(atoms: Atom3D[]): [number, number][] {
  const bonds: [number, number][] = [];
  for (let i = 0; i < atoms.length; i++) {
    for (let j = i + 1; j < atoms.length; j++) {
      const ri = COVALENT_RADII_BOHR[atoms[i].symbol] ?? DEFAULT_COVALENT_RADIUS_BOHR;
      const rj = COVALENT_RADII_BOHR[atoms[j].symbol] ?? DEFAULT_COVALENT_RADIUS_BOHR;
      const dx = atoms[j].position[0] - atoms[i].position[0];
      const dy = atoms[j].position[1] - atoms[i].position[1];
      const dz = atoms[j].position[2] - atoms[i].position[2];
      const dist = Math.sqrt(dx * dx + dy * dy + dz * dz);
      if (dist < BOND_TOLERANCE * (ri + rj) && dist > 0.01) {
        bonds.push([i, j]);
      }
    }
  }
  return bonds;
}

/**
 * Generate a complete POV-Ray scene file from molecular data.
 *
 * The scene includes:
 * - Camera positioned to view the molecule from the +z direction
 * - Area light for soft shadows
 * - CPK-colored atom spheres with glossy finish
 * - Bond cylinders (two-toned, split at midpoint)
 * - White background
 *
 * Coordinates are converted from bohr to Angstrom for conventional scaling.
 */
export function generatePovRay(
  atoms: Atom3D[],
  title?: string,
  orbitalMesh?: { positive: LobeMeshData | null; negative: LobeMeshData | null },
  camera?: CameraState,
): string {
  const s = BOHR_TO_ANGSTROM; // coordinate scale: bohr → Angstrom
  // POV-Ray uses left-handed coordinates; Three.js uses right-handed.
  // Negate Z to convert: pov_z = -three_z.
  const zFlip = -1;
  const rScale = SPHERE_RADIUS_SCALE * s; // sphere radius scale
  const bondRadius = 0.08; // bond cylinder radius in Angstrom

  // Compute center of mass for camera targeting
  let cx = 0, cy = 0, cz = 0;
  for (const a of atoms) {
    cx += a.position[0]; cy += a.position[1]; cz += a.position[2];
  }
  cx = cx / atoms.length * s;
  cy = cy / atoms.length * s;
  cz = cz / atoms.length * s * zFlip;

  // Compute bounding sphere for camera distance (fallback)
  let maxR = 0;
  for (const a of atoms) {
    const dx = a.position[0] * s - cx;
    const dy = a.position[1] * s - cy;
    const dz = a.position[2] * s * zFlip - cz;
    maxR = Math.max(maxR, Math.sqrt(dx * dx + dy * dy + dz * dz));
  }
  const defaultCamDist = maxR * 3.5 + 2;

  // Camera position: use viewer's camera state if available, otherwise default
  let camX: number, camY: number, camZ: number;
  let lookX: number, lookY: number, lookZ: number;

  if (camera) {
    // Use the actual camera position and target from the 3D viewer.
    // Positions are in bohr (scene coordinates) — convert to Angstrom.
    // Z is negated for POV-Ray's left-handed coordinate system.
    lookX = camera.target[0] * s;
    lookY = camera.target[1] * s;
    lookZ = camera.target[2] * s * zFlip;
    camX = camera.position[0] * s;
    camY = camera.position[1] * s;
    camZ = camera.position[2] * s * zFlip;
  } else {
    camX = cx;
    camY = cy;
    camZ = cz + defaultCamDist; // +z in POV-Ray left-handed = looking from front
    lookX = cx;
    lookY = cy;
    lookZ = cz;
  }

  const bonds = detectBonds(atoms);

  const lines: string[] = [];
  lines.push(`// POV-Ray scene generated by IQCP (https://iqcp.dev)`);
  lines.push(`// ${title ?? 'Molecular structure'}`);
  lines.push(`// Render: povray +W1600 +H1200 +A +Q9 molecule.pov`);
  lines.push('');
  lines.push('#version 3.7;');
  lines.push('global_settings { assumed_gamma 1.0 }');
  lines.push('');

  // Background
  lines.push('background { color rgb<0.97, 0.98, 0.99> }');
  lines.push('');

  // Camera (matches viewer orientation when available)
  const camDist = Math.sqrt((camX - lookX) ** 2 + (camY - lookY) ** 2 + (camZ - lookZ) ** 2);
  lines.push(`camera {`);
  lines.push(`  location <${camX.toFixed(4)}, ${camY.toFixed(4)}, ${camZ.toFixed(4)}>`);
  lines.push(`  look_at <${lookX.toFixed(4)}, ${lookY.toFixed(4)}, ${lookZ.toFixed(4)}>`);
  // Three.js uses VERTICAL fov (50°). POV-Ray's `angle` with
  // `right x*image_width/image_height` is HORIZONTAL fov.
  // Convert: h_fov = 2 * atan(tan(v_fov/2) * aspect)
  // For 1600x1200 (4:3): h_fov = 2*atan(tan(25°)*1.333) ≈ 63.8°
  // For 1600x900 (16:9): h_fov = 2*atan(tan(25°)*1.778) ≈ 79.3°
  // Use 4:3 as default (matches our render resolution).
  const vFovRad = (50 / 2) * Math.PI / 180; // half of Three.js fov
  const aspect = 1600 / 1200;
  const hFovDeg = 2 * Math.atan(Math.tan(vFovRad) * aspect) * 180 / Math.PI;
  lines.push(`  angle ${hFovDeg.toFixed(1)}`);
  lines.push(`  right x*image_width/image_height`);
  lines.push(`}`);
  lines.push('');

  // Lighting (positioned relative to camera for consistent illumination)
  // Key light: above-right of camera
  const lightOffsetX = (camX - lookX) * 0.3 + camDist * 0.5;
  const lightOffsetY = camDist * 0.6;
  const lightOffsetZ = (camZ - lookZ) * 0.3;
  lines.push(`// Key light (area light for soft shadows)`);
  lines.push(`light_source {`);
  lines.push(`  <${(camX + lightOffsetX).toFixed(2)}, ${(camY + lightOffsetY).toFixed(2)}, ${(camZ + lightOffsetZ).toFixed(2)}>`);
  lines.push(`  color rgb<1, 1, 1> * 0.85`);
  lines.push(`  area_light <2, 0, 0>, <0, 2, 0>, 5, 5`);
  lines.push(`  adaptive 1 jitter`);
  lines.push(`}`);
  lines.push(`// Fill light (opposite side)`);
  lines.push(`light_source {`);
  lines.push(`  <${(camX - lightOffsetX * 0.6).toFixed(2)}, ${(camY - lightOffsetY * 0.3).toFixed(2)}, ${(camZ - lightOffsetZ * 0.6).toFixed(2)}>`);
  lines.push(`  color rgb<0.6, 0.65, 0.7> * 0.5`);
  lines.push(`}`);
  lines.push('');

  // Material definitions
  lines.push('// Atom material: glossy CPK sphere');
  lines.push('#declare AtomFinish = finish {');
  lines.push('  ambient 0.15');
  lines.push('  diffuse 0.7');
  lines.push('  specular 0.5');
  lines.push('  roughness 0.02');
  lines.push('  reflection 0.03');
  lines.push('};');
  lines.push('');
  lines.push('#declare BondFinish = finish {');
  lines.push('  ambient 0.1');
  lines.push('  diffuse 0.6');
  lines.push('  specular 0.3');
  lines.push('  roughness 0.05');
  lines.push('};');
  lines.push('');

  // Atoms
  lines.push('// === Atoms ===');
  for (let i = 0; i < atoms.length; i++) {
    const a = atoms[i];
    const x = a.position[0] * s;
    const y = a.position[1] * s;
    const z = a.position[2] * s * zFlip;
    const r = (COVALENT_RADII_BOHR[a.symbol] ?? DEFAULT_COVALENT_RADIUS_BOHR) * rScale;
    const color = CPK_COLORS[a.symbol] ?? DEFAULT_ATOM_COLOR;

    // Special case: H is white — darken slightly so it's visible on white background
    const povColor = a.symbol === 'H' ? 'rgb<0.85, 0.85, 0.85>' : hexToPoV(color);

    lines.push(`sphere { // ${a.symbol}(${i})`);
    lines.push(`  <${x.toFixed(6)}, ${y.toFixed(6)}, ${z.toFixed(6)}>, ${r.toFixed(4)}`);
    lines.push(`  pigment { color ${povColor} }`);
    lines.push(`  finish { AtomFinish }`);
    lines.push(`}`);
  }
  lines.push('');

  // Bonds (two-toned cylinders split at midpoint)
  if (bonds.length > 0) {
    lines.push('// === Bonds ===');
    for (const [i, j] of bonds) {
      const ai = atoms[i], aj = atoms[j];
      const x1 = ai.position[0] * s, y1 = ai.position[1] * s, z1 = ai.position[2] * s * zFlip;
      const x2 = aj.position[0] * s, y2 = aj.position[1] * s, z2 = aj.position[2] * s * zFlip;
      const mx = (x1 + x2) / 2, my = (y1 + y2) / 2, mz = (z1 + z2) / 2;

      const colorI = ai.symbol === 'H' ? 'rgb<0.85, 0.85, 0.85>' : hexToPoV(CPK_COLORS[ai.symbol] ?? DEFAULT_ATOM_COLOR);
      const colorJ = aj.symbol === 'H' ? 'rgb<0.85, 0.85, 0.85>' : hexToPoV(CPK_COLORS[aj.symbol] ?? DEFAULT_ATOM_COLOR);

      lines.push(`cylinder { // ${ai.symbol}(${i})-${aj.symbol}(${j})`);
      lines.push(`  <${x1.toFixed(6)}, ${y1.toFixed(6)}, ${z1.toFixed(6)}>,`);
      lines.push(`  <${mx.toFixed(6)}, ${my.toFixed(6)}, ${mz.toFixed(6)}>, ${bondRadius}`);
      lines.push(`  pigment { color ${colorI} }`);
      lines.push(`  finish { BondFinish }`);
      lines.push(`}`);
      lines.push(`cylinder {`);
      lines.push(`  <${mx.toFixed(6)}, ${my.toFixed(6)}, ${mz.toFixed(6)}>,`);
      lines.push(`  <${x2.toFixed(6)}, ${y2.toFixed(6)}, ${z2.toFixed(6)}>, ${bondRadius}`);
      lines.push(`  pigment { color ${colorJ} }`);
      lines.push(`  finish { BondFinish }`);
      lines.push(`}`);
    }
  }

  // Orbital isosurface meshes (positive = blue, negative = red)
  if (orbitalMesh) {
    const lobes: [LobeMeshData | null, string, string][] = [
      [orbitalMesh.positive, 'Positive lobe', 'rgb<0.27, 0.53, 1.0>'],   // #4488ff blue
      [orbitalMesh.negative, 'Negative lobe', 'rgb<1.0, 0.27, 0.27>'],   // #ff4444 red
    ];

    for (const [lobe, label, color] of lobes) {
      if (!lobe || lobe.vertices.length === 0 || lobe.indices.length === 0) continue;

      const nVerts = lobe.vertices.length / 3;
      const nTris = lobe.indices.length / 3;

      lines.push('');
      lines.push(`// === ${label} (${nVerts} vertices, ${nTris} triangles) ===`);
      lines.push('mesh2 {');

      // Vertex vectors (positions are already in bohr from marching cubes — convert to Angstrom)
      lines.push(`  vertex_vectors {`);
      lines.push(`    ${nVerts},`);
      for (let v = 0; v < nVerts; v++) {
        const x = lobe.vertices[v * 3] * s;
        const y = lobe.vertices[v * 3 + 1] * s;
        const z = lobe.vertices[v * 3 + 2] * s * zFlip;
        const comma = v < nVerts - 1 ? ',' : '';
        lines.push(`    <${x.toFixed(6)}, ${y.toFixed(6)}, ${z.toFixed(6)}>${comma}`);
      }
      lines.push(`  }`);

      // Normal vectors
      if (lobe.normals.length === lobe.vertices.length) {
        lines.push(`  normal_vectors {`);
        lines.push(`    ${nVerts},`);
        for (let v = 0; v < nVerts; v++) {
          const nx = lobe.normals[v * 3];
          const ny = lobe.normals[v * 3 + 1];
          const nz = lobe.normals[v * 3 + 2] * zFlip;
          const comma = v < nVerts - 1 ? ',' : '';
          lines.push(`    <${nx.toFixed(6)}, ${ny.toFixed(6)}, ${nz.toFixed(6)}>${comma}`);
        }
        lines.push(`  }`);
      }

      // Face indices
      lines.push(`  face_indices {`);
      lines.push(`    ${nTris},`);
      for (let t = 0; t < nTris; t++) {
        // Swap winding order (i1 <-> i2) to compensate for Z-flip
        const i0 = lobe.indices[t * 3];
        const i1 = lobe.indices[t * 3 + 2];
        const i2 = lobe.indices[t * 3 + 1];
        const comma = t < nTris - 1 ? ',' : '';
        lines.push(`    <${i0}, ${i1}, ${i2}>${comma}`);
      }
      lines.push(`  }`);

      // Material: semi-transparent with smooth shading
      lines.push(`  pigment { color ${color} filter 0.85 }`);
      lines.push(`  finish {`);
      lines.push(`    ambient 0.1`);
      lines.push(`    diffuse 0.7`);
      lines.push(`    specular 0.4`);
      lines.push(`    roughness 0.01`);
      lines.push(`    reflection 0.05`);
      lines.push(`  }`);
      lines.push(`  interior { ior 1.1 }`);
      lines.push('}');
    }
  }

  return lines.join('\n');
}

/**
 * Download a POV-Ray file for the given molecular structure.
 */
export function downloadPovRay(
  atoms: Atom3D[],
  filename?: string,
  title?: string,
  orbitalMesh?: { positive: LobeMeshData | null; negative: LobeMeshData | null },
  camera?: CameraState,
): void {
  const content = generatePovRay(atoms, title, orbitalMesh, camera);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename ?? 'iqcp-molecule.pov';
  a.click();
  URL.revokeObjectURL(url);
}
