[package]
name = "qc-io"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Shared data schemas for IQCP (RunState, RunArtifact)"

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
approx.workspace = true
